add forgot password
vladysllav/wellplan pull request #28
Opened 2023-10-04 16:37 UTC by AlexGrig23

2023-10-05 14:27 UTC, vladysllav requested changes
Не бачу як це буде працювати, відправляти ти відправляеш, а де ендпоінт який буде перевіряти токен та запитувати новий пароль. Потрібно зробити другий ендпоінт який буде приймати токен та пароль, перевіряти токен, за токеном знаходити юзера і сетати новий пароль

2023-10-05 14:27 UTC, vladysllav commented on .env.example
> +TEMP_TOKEN_EXPIRE_MINUTES=10
Перейменуй у FORGOT_PASSWORD_TOKEN_EXPIRE_MINUTES

2023-10-05 14:27 UTC, vladysllav commented on app/api/auth/routes.py
> +    base_url = "http://127.0.0.1:8000/"  # test url
Це потрібно брати з конфігу

2023-10-05 14:27 UTC, vladysllav commented on app/email.py
> +    smtp_server = "smtp.gmail.com"
Це також у конфіг винеси

2023-10-06 13:49 UTC, AlexGrig23 commented on .env.example
> +TEMP_TOKEN_EXPIRE_MINUTES=10
Пофіксив

2023-10-06 13:50 UTC, AlexGrig23 commented on app/api/auth/routes.py
> +    base_url = "http://127.0.0.1:8000/"  # test url
Пофіксив

2023-10-06 13:54 UTC, AlexGrig23 commented on app/email.py
> +    smtp_server = "smtp.gmail.com"
Пофіксив

2023-10-06 13:59 UTC, AlexGrig23 commented
Всі зауваження пофіксив.

2023-10-19 05:28 UTC, merged