create users model and make migration
vladysllav/wellplan pull request #3
Opened 2023-09-19 20:29 UTC by AlexGrig23

Create users model, make migrations, connection DB

2023-09-19 21:34 UTC, andreichukdev commented
Швидше за все мені треба буде поле is_superuser в базовій UserSchema, щоб можна було в CRUD додати функцію, яка тягне це поле, щоб написати скрипт для створення superuser, його можна зробити опціональним 
@vladysllav чи я помиляюсь?

2023-09-20 06:36 UTC, vladysllav requested changes
Потрібно змінити поле user_type

2023-09-20 06:36 UTC, vladysllav commented on app/models/user.py
> +    user_type = Column(Enum('client', 'admin', name='user_type_enum'))
Нам необхідно мати superuser тип, потрібно його також додати до user_type Enum

І краще використовувати окремий класс, щось типу
class UserTypeEnum(enum.Enum):
    client = 'client'
    admin = 'admin'
    superadmin = 'superadmin'

2023-09-20 06:37 UTC, vladysllav commented
> Швидше за все мені треба буде поле is_superuser в базовій UserSchema, щоб можна було в CRUD додати функцію, яка тягне це поле, щоб написати скрипт для створення superuser, його можна зробити опціональним @vladysllav чи я помиляюсь?

Не зовсім, у задачі я прописав що user_type повинен мати superuser тип, використовуй це поле як маркер для суперюзера

2023-09-20 12:36 UTC, merged