Wel 53 fix auth func
vladysllav/wellplan pull request #31
Opened 2023-10-23 17:41 UTC by AlexGrig23

2023-10-23 17:43 UTC, AlexGrig23 commented
Look at the first commit, in the second there are linters

2023-10-25 07:25 UTC, vladysllav requested changes
Пермишны сделаны не просто костыльно, а даже хз как назвать. Я скину в лс как это нужно делать ибо НЕЛЬЗЯ добавлять в dependency метод ендпоинта, будет каша полнейшая

2023-10-25 07:25 UTC, vladysllav commented on app/api/auth/routes.py
> +def auth(access_token: Annotated[str, Depends(apikey_scheme)], db: Session = Depends(deps.get_db)):
А какая логика у этого ендпоинта? ЗАчем он вообще нужен?

2023-10-25 15:43 UTC, AlexGrig23 commented on app/api/auth/routes.py
> +def auth(access_token: Annotated[str, Depends(apikey_scheme)], db: Session = Depends(deps.get_db)):
Сори тестил работу Depends(apikey_scheme) завтыкал удалить. В новом коммите исправил

2023-10-25 15:46 UTC, AlexGrig23 commented
Исправил замечания по пермишенам, улучшил метод current_user, удалил лишний роут @router.post("/authentication")

2023-10-26 01:45 UTC, vladysllav approved these changes

2023-10-26 01:45 UTC, merged