Wel 6 write auth function
vladysllav/wellplan pull request #4
Opened 2023-09-20 14:43 UTC by AlexGrig23

Create security file, add functions create_token, decode_tocen, verify_password, hash_password, and update .env.example

2023-09-20 16:01 UTC, vladysllav requested changes
Все гуд, потрібно лише змінну переназвати

2023-09-20 16:01 UTC, vladysllav commented on .env.example
> +ALGORITHM = ""
Це поле не потрібно робити константним, просто передавати прямо до функції буде ок

2023-09-20 16:01 UTC, vladysllav commented on .env.example
> +ALGORITHM = ""
Або хочаб перейменуй так щоб було зрозуміло що це за алгоритм, бо неоднозначна назва, а так можеш залишити, тут не принципово

2023-09-21 10:46 UTC, andreichukdev commented
перейменуй файл з маленької security.py і бажано щоб від знаходився в app/core/security.py це з точки зору розмежування та архітектури більш відома практика

2023-09-21 12:59 UTC, andreichukdev approved these changes

2023-09-23 14:25 UTC, closed without merging